let employees = [{ "id": 1, "name": "Lib", "email": "lswendell0@theatlantic.com", "gender": "Female" },
{ "id": 2, "name": "Ewell", "email": "ecosgriff1@domainmarket.com", "gender": "Male" },
{ "id": 3, "name": "Mathilda", "email": "mdaughtrey2@techcrunch.com", "gender": "Female" },
{ "id": 4, "name": "Feodor", "email": "fdelgua3@nationalgeographic.com", "gender": "Male" },
{ "id": 5, "name": "Jayme", "email": "jtzar4@fda.gov", "gender": "Female" },
{ "id": 6, "name": "Esmeralda", "email": "emardle5@behance.net", "gender": "Female" },
{ "id": 7, "name": "Margie", "email": "mdewire6@rambler.ru", "gender": "Female" },
{ "id": 8, "name": "Tedman", "email": "thawford7@cbslocal.com", "gender": "Male" },
{ "id": 9, "name": "Noak", "email": "nwemes8@house.gov", "gender": "Male" },
{ "id": 10, "name": "Barty", "email": "bbrownell9@wufoo.com", "gender": "Male" },
{ "id": 11, "name": "Sharla", "email": "svonnassaua@gov.uk", "gender": "Female" },
{ "id": 12, "name": "Hilly", "email": "hstormouthb@tuttocitta.it", "gender": "Male" },
{ "id": 13, "name": "Raina", "email": "rbenec@pen.io", "gender": "Female" },
{ "id": 14, "name": "Web", "email": "wgauchd@scientificamerican.com", "gender": "Male" },
{ "id": 15, "name": "Florian", "email": "fpancoste@gizmodo.com", "gender": "Male" },
{ "id": 16, "name": "Garald", "email": "ggramerf@sogou.com", "gender": "Male" },
{ "id": 17, "name": "Dee dee", "email": "dclasheg@wsj.com", "gender": "Female" },
{ "id": 18, "name": "Terri", "email": "tivachyovh@illinois.edu", "gender": "Female" },
{ "id": 19, "name": "Essy", "email": "etironi@indiegogo.com", "gender": "Female" },
{ "id": 20, "name": "Ramsey", "email": "rwishamj@printfriendly.com", "gender": "Male" }]

export default employees